### PR TITLE
give kakapo-mode its own separate word in the modeline

### PR DESCRIPTION
**Pull request by mat8913**
Fixes the string getting stuck to others in the modeline.

### CODE REVIEW

**Comment by listx** [comment]
Hmm, actually this is not a bug --- it was an intentional design choice when I first wrote it as such. The idea was that kakapo-mode was so insignificant/unimportant that I felt it didn't deserve standing on its own as a separate word in the modeline.

But I realize now that that was probably a poor decision choice. I would merge, but I think that the leading slash should also be removed, to be just " kkp" and not " /kkp".

**Comment by mat8913** [comment]
Would you prefer I add a new commit, or squash the changes into this one?

**Comment by listx** [comment]
I would prefer it squashed into 1 commit, thanks.

**Comment by mat8913** [comment]
Done

**Comment by listx** [comment]
Thanks!

**Pull request merged**
